Banner image fix
datadryad/dryad-repo pull request #1297
Opened 2017-04-17 05:54 UTC by ryscher

Fix for the banner widget API issue described in https://trello.com/c/FZ8NlcnE

Before applying this fix, the banner API will not produce banners for DOIs of publications, such as

http://datadryad.org/widgets/bannerForPub?referrer=test&pubId=doi:10.1111/j.1558-5646.2007.00022.x

After applying the fix, URLs like the above should return a banner image stating "Data in Dryad", provided the DOI refers to a publication that appears in one of the data packages for the server.

2017-04-20 18:09 UTC, daisieh requested changes
Are these real changes?

2017-04-20 18:10 UTC, daisieh commented on dspace/modules/dryad-widgets/dryad-widgets-webapp/src/main/java/org/dspace/app/xmlui/aspect/dryadwidgets/WidgetBannerSelector.java
> -        return packageDOI != null;
Is this actually different?

2017-04-20 18:10 UTC, daisieh commented on dspace/modules/dryad-widgets/dryad-widgets-webapp/src/main/java/org/dspace/app/xmlui/aspect/dryadwidgets/WidgetBannerLookup.java
> -
This file is changed just for a spacing change?

2017-04-21 20:48 UTC, ryscher commented on dspace/modules/dryad-widgets/dryad-widgets-webapp/src/main/java/org/dspace/app/xmlui/aspect/dryadwidgets/WidgetBannerLookup.java
> -
Side effect of adding/removing logging. I can revert it.

2017-04-21 20:48 UTC, ryscher commented on dspace/modules/dryad-widgets/dryad-widgets-webapp/src/main/java/org/dspace/app/xmlui/aspect/dryadwidgets/WidgetBannerSelector.java
> -        return packageDOI != null;
Another side effect of adding/removing logging.

2017-04-25 17:59 UTC, daisieh commented
Looks like this works on my VM. Merging.

2017-04-25 17:59 UTC, merged