Improve logging for exceptions in DOI creation
datadryad/dryad-repo pull request #1313
Opened 2017-06-07 20:11 UTC by ryscher

2017-06-07 23:03 UTC, daisieh requested changes
Did you check this on your VM? When I try to compile, ti complains a lot about unhandled exceptions.

2017-06-08 01:42 UTC, ryscher commented
oops, here's the rest....

2017-06-08 06:12 UTC, daisieh approved these changes

2017-06-08 06:12 UTC, daisieh commented
Looks fine, builds this time. Merging.

2017-06-08 06:12 UTC, merged