Dash transfer -- initial version
datadryad/dryad-repo pull request #1477
Opened 2018-10-08 05:25 UTC by ryscher

This is the first version of the transfer mechanism between classic Dryad and New Dryad. It transfers basic metadata about a data package (title, authors, abstract). It can be run over a single data package, or the entire collection of data packages.

To test:
1. Ensure your maven settings file has appropriate values for 
  - default.dash.server = protocol and hostname of the target server (e.g. http://ryandash.datadryad.org)
  - default.dash.username = oauth application ID
  - default.dash.password = oauth application secret
2. Find the handle of an item you want to transfer
3. Call the tool from the command line, using the handle as the item's ID:
`/opt/dryad/bin/dspace curate -v -t transfertodash -i 10255/dryad.135814 -r -`

If you want to transfer all data packages, use the handle of the Data Packages collection (usually 10255/3).

Caveats:
- Although this PR includes a definition for a new metadata field, dashTransferDate, this field is not yet used. It will be used in a future update.
- The CSV written to stdout is intended to give basic feedback for someone watching the script run. It has been copied from the old DataPackageStats report, and currently contains some fields that do not yet have values. These values will be added in a future update.

2018-10-09 22:56 UTC, daisieh commented on dspace/config/dspace.cfg
> +dash.username = ${default.dash.username}
Can you change these to match the new system's terminology? i.e. `client_id` instead of `username` and `client_secret` instead of `password`?

2018-10-09 23:15 UTC, daisieh requested changes
This is a pretty nitpicky thing to complain about, but can you re-format the code so that the indents are correct or at least consistent to a single style? Also, can you either add comments as to why there are unused variables and methods in the class, or delete the unused ones entirely?

I'd also consider whether or not some of these methods should be factored out into more accessible classes: I've been writing my own code for getting a bearer token, etc., and it'd probably be best for you to check this code into one central place where I can access it too. Perhaps we should have a more centralized class with methods for talking to the Dash API.

2018-10-11 01:26 UTC, daisieh commented
Another question: I notice that the json that you're sending has authors associated with the publication, but no authors associated with the data package itself. Is that the correct intention?

2018-10-11 14:20 UTC, ryscher commented
> Another question: I notice that the json that you're sending has authors associated with the publication, but no authors associated with the data package itself. Is that the correct intention?

The authors are listed *after* the publication information, but they're not associated with the publication. They're at the top level (dataset).

2018-10-11 17:55 UTC, daisieh commented on dspace/modules/api/src/main/java/org/dspace/curate/TransferToDash.java
> +            connection.setRequestMethod("POST");
FYI: I'm trying to parse this out with @sfisher right now, but apparently he and @dmoles think that if you want to create a new entry that specifies the identifier (like with a specific DOI), you should do a PUT. I don't agree with this behavior, but that's what it's doing right now.

2018-10-11 18:24 UTC, daisieh commented on dspace/modules/api/src/main/java/org/dspace/curate/TransferToDash.java
> +            connection.setRequestMethod("POST");
FYI after discussing this for quite a bit with @sfisher, I am convinced that PUT is in fact the correct behavior. We need to fix the response behavior, though. https://github.com/CDL-Dryad/dryad-product-roadmap/issues/106

2018-10-15 00:15 UTC, ryscher commented
Closing since this is now replaced with #1480

2018-10-15 00:15 UTC, closed without merging